README.md
In the readme it says to run yanagishima-stop to stop the server.  Actually the command is yanagishima-shutdown.
=> correct the name of the shutdown command

src/main/java/yanagishima/config/YanagishimaConfig.java, src/main/java/yanagishima/module/HiveServletModule.java, src/main/java/yanagishima/service/HiveService.java, src/main/java/yanagishima/service/HiveServiceImpl.java, src/main/java/yanagishima/servlet/HiveAsyncServlet.java, src/main/java/yanagishima/servlet/HivePartitionServlet.java, src/main/java/yanagishima/servlet/HiveQueryDetailServlet.java, src/main/java/yanagishima/servlet/HiveQueryStatusServlet.java, src/main/java/yanagishima/servlet/HiveServlet.java, src/main/java/yanagishima/servlet/SparkJobListServlet.java, src/main/java/yanagishima/util/HistoryUtil.java, src/main/java/yanagishima/util/SparkUtil.java
submit sparksql with Hive JDBC Driver through Thrift JDBC/ODBC server
https://spark.apache.org/docs/latest/sql-distributed-sql-engine.html
Unfortunately, we can't track progress because we can't specify spark jobId through rest api
https://spark.apache.org/docs/latest/monitoring.html
=> support sparksql

README.md, src/main/java/yanagishima/config/YanagishimaConfig.java, src/main/java/yanagishima/service/PrestoServiceImpl.java
Update YanagishimaConfig	
`public String getUser(String datasource) {`
`    String user = properties.getProperty("user." + datasource);`
`    if (user == null) {`
`        user = "yanagishima";`
`    }`
`    return user;`
`}`
`public String getSource(String datasource) {`
`    String source = properties.getProperty("source." + datasource);`
`    if (source == null) {`
`        source = "yanagishima";`
`    }`
`    return source;`
`}`
Repair error: Query did not match any selection rule
Thank you. Yanagishima.
=> update config add user and source

src/main/java/yanagishima/config/YanagishimaConfig.java, src/main/java/yanagishima/service/HiveServiceImpl.java
https://www.cloudera.com/documentation/enterprise/5-8-x/topics/cdh_sg_hiveserver2_security.html#concept_vjq_c3x_nm
=> Add hive impersonation logic

web/src/api/index.js, web/src/components/tabs/TabTreeview.vue
Fix https://github.com/yanagishima/yanagishima/issues/65
=> Add missing double quotation

src/main/java/yanagishima/util/PathUtil.java, src/test/java/yanagishima/util/PathUtilTest.java
File#mkdirs is sufficient in this case. 
Ref: https://docs.oracle.com/javase/7/docs/api/java/io/File.html#mkdirs()
=> Refactor PathUtil class

src/main/java/yanagishima/servlet/PublishServlet.java
About existing `publish` method: Please don't pass mutable Map object to be modified in the called method. The scope is too wide and it makes hard to understand the entire code.
=> Cleanup PublishServlet class

src/main/java/yanagishima/config/YanagishimaConfig.java, src/main/java/yanagishima/service/ElasticsearchServiceImpl.java, src/main/java/yanagishima/service/HiveServiceImpl.java, src/main/java/yanagishima/service/OldPrestoServiceImpl.java, src/main/java/yanagishima/service/PrestoServiceImpl.java
=> Increase max-result-file-byte-size to long

build.gradle
To improve readability of test result:
=> Apply gradle test logger plugin

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/QueryDetailServlet.java, src/package/conf/yanagishima.properties
=> Migrate query detail servlet to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/ShareDownloadServlet.java
=> Migrate share download servlet to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/DownloadServlet.java
=> Migrate download servlet to spring

src/main/java/yanagishima/model/HttpRequestContext.java, src/main/java/yanagishima/model/db/Bookmark.java, src/main/java/yanagishima/model/dto/BookmarkCreateDto.java, src/main/java/yanagishima/model/dto/BookmarkDto.java, src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/BookmarkServlet.java, src/main/java/yanagishima/servlet/BookmarkUserServlet.java
=> Migrate bookmark servlets to spring

src/main/java/yanagishima/model/dto/PublishDto.java, src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/PublishServlet.java
Note: It seems FE doesn't handle returned error correctly even before this change. 
↓
=> Migrate publish servlet to spring

build.gradle, src/main/java/yanagishima/config/DataConfig.java, src/main/java/yanagishima/model/db/Bookmark.java, src/main/java/yanagishima/repository/BookmarkRepository.java, src/main/java/yanagishima/repository/TinyOrm.java, src/main/java/yanagishima/service/BookmarkService.java, src/main/java/yanagishima/servlet/BookmarkServlet.java, src/main/java/yanagishima/servlet/BookmarkUserServlet.java, src/test/java/yanagishima/repository/TinyOrmTest.java
https://user-images.githubusercontent.com/6237050/102566788-8a9ae580-4123-11eb-858e-7c41d2a4fbb1.mov
=> Apply Spring Data JPA to bookmark

build.gradle, src/main/java/yanagishima/config/SwaggerConfig.java, src/main/java/yanagishima/config/WebMvcConfig.java, src/main/java/yanagishima/servlet/BookmarkServlet.java, src/main/java/yanagishima/servlet/BookmarkUserServlet.java, src/main/java/yanagishima/servlet/ConvertHiveServlet.java, src/main/java/yanagishima/servlet/ConvertPrestoServlet.java, src/main/java/yanagishima/servlet/DownloadServlet.java, src/main/java/yanagishima/servlet/HealthCheckServlet.java, src/main/java/yanagishima/servlet/PublishServlet.java, src/main/java/yanagishima/servlet/QueryDetailServlet.java, src/main/java/yanagishima/servlet/ShareDownloadServlet.java
=> Add support for swagger ui

src/main/java/yanagishima/model/db/StarredSchema.java, src/main/java/yanagishima/model/dto/StarredSchemaCreateDto.java, src/main/java/yanagishima/model/dto/StarredSchemaDto.java, src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/StarredSchemaServlet.java
https://user-images.githubusercontent.com/6237050/102625354-b603eb80-4188-11eb-98ec-4a14176924d7.mov
=> Migrate starred schema servlet to spring

build.gradle, src/test/java/yanagishima/config/YanagishimaConfigTest.java, src/test/java/yanagishima/repository/TinyOrmTest.java, src/test/java/yanagishima/util/HttpRequestUtilTest.java, src/test/java/yanagishima/util/PathUtilTest.java, src/test/java/yanagishima/util/SparkUtilTest.java, src/test/java/yanagishima/util/YarnUtilTest.java
=> Upgrade junit to 5.7.0

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/ShareCsvDownloadServlet.java
```bash
$ curl -s 'http://localhost:8080/share/csvdownload?publish_id=2e4165e796960ef8e4f12cc1557630f2'
_col0
1
```
=> Migrate share csv download servlet to spring

docker/mysql/docker-compose.yml, src/main/java/yanagishima/model/db/StarredSchema.java, src/package/conf/yanagishima.properties
Fixes #231
Let me change yanagishima.properties so that we can use mysql as backend db by default.
=> Quote reserved column name in starred schema

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/PrestoPartitionServlet.java
=> Migrate Presto partition servlet to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/CheckPrestoQueryServlet.java
```bash
$ curl -sS -X POST 'http://localhost:8080/checkPrestoQuery?datasource=docker-presto&query=SELECT%20*%20FROM%20system.runtime.nodes' -H 'some.auth.header: foo' | jq
{
"physicalInputDataSize": "38B",
"physicalInputPositions": 1
}
```
=> Migrate Presto check query servlet to spring

src/main/java/yanagishima/model/db/Publish.java, src/main/java/yanagishima/repository/PublishRepository.java, src/main/java/yanagishima/repository/TinyOrm.java, src/main/java/yanagishima/service/PublishService.java, src/main/java/yanagishima/servlet/PublishServlet.java, src/main/java/yanagishima/servlet/ShareCsvDownloadServlet.java, src/main/java/yanagishima/servlet/ShareDownloadServlet.java, src/main/java/yanagishima/servlet/ShareHistoryServlet.java, src/test/java/yanagishima/repository/TinyOrmTest.java
https://user-images.githubusercontent.com/6237050/102974130-5ff4c680-4541-11eb-9d72-ea502d985938.mov
=> Migrate publish to Spring Data JPA

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/QueryServlet.java
`Object` should be changed to DTO class later. Query List tab calls `/query` api. 
https://user-images.githubusercontent.com/6237050/102962762-ddf9a300-452a-11eb-9fcc-541f2439da54.mov
=> Migrate query servlet to spring

src/main/java/yanagishima/bean/BeanProvider.java, src/main/java/yanagishima/module/HiveServletModule.java, src/main/java/yanagishima/servlet/HiveAsyncServlet.java, src/main/java/yanagishima/servlet/HiveServlet.java
https://user-images.githubusercontent.com/6237050/102953992-e2679100-4515-11eb-84ad-5ce29537c96e.mov
=> Migrate Hive servlets to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/PrestoServlet.java
https://user-images.githubusercontent.com/6237050/102949010-9105d480-450a-11eb-91d0-89fe546375a2.mov
=> Migrate Presto servlet to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/PrestoKillServlet.java
https://user-images.githubusercontent.com/6237050/102837356-fb514300-443e-11eb-9858-977349923c69.mov
=> Migrate Presto kill servlet to spring

src/main/java/yanagishima/model/dto/HistoryStatusDto.java, src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/HistoryStatusServlet.java
```bash
$ curl -s 'http://localhost:8080/historyStatus?datasource=docker-presto&queryid=20201217_110238_00010_9ej6w'
{"status":"ok","error":null}
$ curl -s 'http://localhost:8080/historyStatus?datasource=docker-presto&queryid=xxx'
{"status":"ng","error":null}
```
=> Migrate history status servlet to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/CommentServlet.java
https://user-images.githubusercontent.com/6237050/102843057-c0a1d780-444b-11eb-8fc2-1b688c833c52.mov
=> Migrate comment servlet to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/CsvDownloadServlet.java
=> Migrate csv download servlet to spring

src/main/java/yanagishima/controller/ControllerExceptionHandler.java, src/main/java/yanagishima/exception/YanagishimaParseException.java, src/main/java/yanagishima/model/ParseErrorResponse.java, src/main/java/yanagishima/model/dto/FormatSqlDto.java, src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/FormatSqlServlet.java
=> Migrate format sql servlet to spring

src/main/java/yanagishima/module/HiveServletModule.java, src/main/java/yanagishima/servlet/HivePartitionServlet.java
=> Migrate Hive partition servlet to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/QueryStatusServlet.java
```bash
$ curl -sS -X POST 'http://localhost:8080/queryStatus?datasource=docker-presto&queryid=20201224_023009_00033_f9fa9' -H 'some.auth.header: foo'
{"queryId":"20201224_023009_00033_f9fa9","state":"FINISHED","memoryPool":"general","scheduled":true,"self":"http://172.29.0.2:8080/v1/query/20201224_023009_00033_f9fa9","fieldNames":["partkey","name","mfgr","brand","type","size","container","retailprice","comment"],...
```
=> Migrate query status servlet to spring

src/main/java/yanagishima/module/HiveServletModule.java, src/main/java/yanagishima/servlet/YarnJobListServlet.java
=> Migrate Yarn job list servlet to spring

src/main/java/yanagishima/module/PrestoServletModule.java, src/main/java/yanagishima/servlet/QueryHistoryUserServlet.java
=> Migrate query history user servlet to spring

src/main/java/yanagishima/servlet/QueryHistoryServlet.java, src/main/java/yanagishima/servlet/QueryHistoryUserServlet.java
=> Ignore label in query history

src/main/java/yanagishima/annotation/DatasourceAuth.java, src/main/java/yanagishima/config/WebMvcConfig.java, src/main/java/yanagishima/interceptor/DatasourceInterceptor.java, src/main/java/yanagishima/servlet/CommentServlet.java
I would apply to other places once we agree on this approach. 
Related to #268
=> Introduce datasource interceptor to comment api

src/main/java/yanagishima/servlet/BookmarkServlet.java, src/main/java/yanagishima/servlet/BookmarkUserServlet.java, src/main/java/yanagishima/servlet/CheckPrestoQueryServlet.java, src/main/java/yanagishima/servlet/CsvDownloadServlet.java, src/main/java/yanagishima/servlet/DownloadServlet.java, src/main/java/yanagishima/servlet/ElasticsearchQueryStatusServlet.java, src/main/java/yanagishima/servlet/ElasticsearchServlet.java, src/main/java/yanagishima/servlet/HistoryServlet.java, src/main/java/yanagishima/servlet/HistoryStatusServlet.java, src/main/java/yanagishima/servlet/HiveAsyncServlet.java, src/main/java/yanagishima/servlet/HivePartitionServlet.java, src/main/java/yanagishima/servlet/HiveQueryDetailServlet.java, src/main/java/yanagishima/servlet/HiveQueryStatusServlet.java, src/main/java/yanagishima/servlet/HiveServlet.java, src/main/java/yanagishima/servlet/KillHiveServlet.java, src/main/java/yanagishima/servlet/LabelServlet.java, src/main/java/yanagishima/servlet/PrestoAsyncServlet.java, src/main/java/yanagishima/servlet/PrestoKillServlet.java, src/main/java/yanagishima/servlet/PrestoPartitionServlet.java, src/main/java/yanagishima/servlet/PrestoServlet.java, src/main/java/yanagishima/servlet/PublishServlet.java, src/main/java/yanagishima/servlet/QueryDetailServlet.java, src/main/java/yanagishima/servlet/QueryHistoryServlet.java, src/main/java/yanagishima/servlet/QueryHistoryUserServlet.java, src/main/java/yanagishima/servlet/QueryServlet.java, src/main/java/yanagishima/servlet/QueryStatusServlet.java, src/main/java/yanagishima/servlet/SparkJobListServlet.java, src/main/java/yanagishima/servlet/StarredSchemaServlet.java, src/main/java/yanagishima/servlet/YarnJobListServlet.java
=> Apply @DatasourceAuth annotation

src/main/java/yanagishima/config/YanagishimaConfig.java, src/main/java/yanagishima/controller/PrestoPartitionController.java
=> Remove support for WebHDFS

src/main/java/yanagishima/config/WebMvcConfig.java, src/main/java/yanagishima/controller/BookmarkController.java, src/main/java/yanagishima/model/User.java, src/main/java/yanagishima/resolver/UserArgumentResolver.java, src/main/java/yanagishima/service/BookmarkService.java
=> Introduce user argument resolver to bookmark controller

src/main/java/yanagishima/controller/CommentController.java, src/main/java/yanagishima/controller/DownloadController.java, src/main/java/yanagishima/controller/ElasticsearchController.java, src/main/java/yanagishima/controller/HistoryController.java, src/main/java/yanagishima/controller/PublishController.java, src/main/java/yanagishima/controller/StarredSchemaController.java, src/main/java/yanagishima/service/CommentService.java, src/main/java/yanagishima/service/PublishService.java, src/main/java/yanagishima/service/QueryService.java, src/main/java/yanagishima/service/StarredSchemaService.java
=> Apply user resolver to some controllers

.github/workflows/main.yml, web/package-lock.json, web/package.json
=> Upgrade node-sass to 4.14.1

src/main/java/yanagishima/config/YanagishimaConfig.java, src/main/java/yanagishima/controller/CheckPrestoQueryController.java, src/main/java/yanagishima/controller/PrestoKillController.java, src/main/java/yanagishima/controller/QueryController.java, src/main/java/yanagishima/controller/QueryStatusController.java, src/main/java/yanagishima/service/OldPrestoService.java, src/main/java/yanagishima/service/PrestoService.java
This example setting in application.yml means principal is yanagishima.
```
presto.impersonation.hoge: true
presto.impersonated.user.hoge: yanagishima
presto.impersonated.password.hoge: password
```
https://trino.io/docs/current/develop/system-access-control.html
=> add presto impersonation logic

src/main/java/yanagishima/config/YanagishimaConfig.java
=> Set 3600 seconds for Hive max runtime by default

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Example: https://github.com/sqlalchemy/sqlalchemy/issues/new/choose
=> Separate issue template into bug report and feature request

build.gradle, src/main/resources/config/application.yml
=> Introduce Spring Actuator

build.gradle, src/main/java/yanagishima/config/SwaggerConfig.java
Additonally, change to Open API from Swagger 2.
=> Upgrade Spring Fox to 3.0.0

build.gradle
This commit changes below version internally.
okhttp: 3.9.0 -> 3.14.9
fluent-hc: 4.4.1 -> 4.5.13
https://docs.spring.io/spring-boot/docs/2.3.5.RELEASE/reference/html/appendix-dependency-versions.html
=> Apply Spring Boot gradle plugin

build.gradle
Additionally, remove unused sonatype repository.
=> Use https maven repositories

docker/hive/docker-compose.yml
Additionally, change port for mysql because it's conflicting with another mysql docker.
=> Use HDP image in ghcr.io

build.gradle, src/test/java/yanagishima/TestHelper.java, src/test/java/yanagishima/controller/ShareControllerTest.java, src/test/resources/config/application.yml
Let's start adding controller tests for important features.
=> Add test for ShareController.get() method

src/main/java/yanagishima/controller/CheckPrestoQueryController.java, src/main/java/yanagishima/controller/PrestoController.java, src/main/java/yanagishima/controller/PrestoPartitionController.java, src/main/java/yanagishima/service/PrestoService.java
=> Don't keep session properties in PrestoService class

build.gradle, gradle/wrapper/gradle-wrapper.properties
Let me rollback to Gradle 5.2 temporarily. Confirmed this commit works correctly. 
Relates to #340
=> Rollback to Gradle 5.2

build.gradle, docs/release.md, web/package.json, web/src/constants/index.js
I was asked about the next release in twitter DM. Let's release 23.0.
=> Release version 23.0

README.md, build.gradle, docker/presto/docker-compose.yml, docker/trino/docker-compose.yml, src/main/java/yanagishima/client/presto/PrestoClient.java, src/main/java/yanagishima/controller/CheckPrestoQueryController.java, src/main/java/yanagishima/controller/PrestoAsyncController.java, src/main/java/yanagishima/controller/PrestoController.java, src/main/java/yanagishima/controller/SqlController.java, src/main/java/yanagishima/service/PrestoService.java, src/main/resources/config/application.yml
=> Upgrade to Trino version 352

docs/config.md
=> Document Spring Boot and MySQL requirement

src/main/java/yanagishima/model/db/Query.java, src/main/java/yanagishima/service/QueryService.java, src/main/java/yanagishima/util/FormatUtil.java, src/main/resources/schema.sql, src/test/java/yanagishima/util/FormatUtilTest.java
Closed #367
Signed-off-by: siu91 <gongshiwen@gmail.com>
=> Fix [Yanagishima] bytes is negative
